### import the module you need first

In [1]:
import numpy as np
from copy import deepcopy

## step1. 
#### Construct a numpy array represent the equations.
#### the coefficients,answers and augmented matrix of each equation need to be stored separately.

In [2]:
"""
example:
 
5y-7z = 7        | 0 5 -7 7 |
4x-z = 8      -> | 4 0 -1 8 |
x-y-z = 9        | 1 -1 -1 9 |
"""
A=np.array([[0,5,-7,7],[4,0,-1,8],[1,-1,-1,9]],dtype=float) #要宣告成float型態
print(A)

[[ 0.  5. -7.  7.]
 [ 4.  0. -1.  8.]
 [ 1. -1. -1.  9.]]


## step2. 
### Before doing gauss elimination,
### we need to check if the first element([0,0]) of the augmented matrix is zero or not.
### If the first element is zero,
### we need to find another row whose first element isn't zero,and change them.

In [3]:
if(A[0,0]==0):
    i=1
    while(A[0,0]==0):
        A[[i,0],:]=A[[0,i],:] #第1列和第(2+n)列互換，n從0遞增     
        #print(A) 確認互換成功
        if(A[0,0]==0): #若換過來還是0，則換回來
            A[[i,0],:]=A[[0,i],:]
            #print(A) 確認有換回來
        i+=1 #繼續嘗試直到成功

In [4]:
#test:step2
#print the new augment matrix
print(A)

[[ 4.  0. -1.  8.]
 [ 0.  5. -7.  7.]
 [ 1. -1. -1.  9.]]


## step3. gauss elimination

#### print the matrix after  gauss elimination

In [5]:
B=np.zeros((3,4),dtype=float) #宣告一個B矩陣存成float型態
B=deepcopy(A) #將A暫存到B，因為等等LU分解還會用到A
for i in range(3): #列
    for j in range(i+1,3): #n+1列
            ratio=B[j][i]/B[i][i] #算比值消掉
            B[j,:]=B[j,:]+B[i,:]*(-ratio)

In [6]:
#test:step3
#print the augment matrix after gauss elimination
print(B)

[[ 4.    0.   -1.    8.  ]
 [ 0.    5.   -7.    7.  ]
 [ 0.    0.   -2.15  8.4 ]]


## step4. LU decomposition(bonus)

## if you don't want to submit bouns,you don't need to do  step4 and step5

In [7]:
import scipy.linalg as la

array_1=A[:,3] #提出第四行元素
#print(array_1) 測試
modified_A=np.delete(A,[3],1) #移除第三行元素
#print(modified_A) 
P,L,U=la.lu(modified_A) #LU decomposition

y=la.solve_triangular(L,array_1,lower=True) #Ly=array_1
x=la.solve_triangular(U,y) #Ux=y

In [8]:
#print L and U
print(L)
print(U)

[[ 1.    0.    0.  ]
 [ 0.    1.    0.  ]
 [ 0.25 -0.2   1.  ]]
[[ 4.    0.   -1.  ]
 [ 0.    5.   -7.  ]
 [ 0.    0.   -2.15]]


## step5. check the ansewer of LU(bonus)

please use the function in scipy.linalg to check your answer

the documentatin of scipy.linalg :
https://docs.scipy.org/doc/scipy/reference/linalg.html

In [9]:
import scipy.linalg as la

In [10]:
check_matrix=np.zeros([3,3]) #宣告一個空白矩陣(其實不用)
check_matrix=L.dot(U) #LU=A,存到空白矩陣裡 
print(check_matrix) 
if(check_matrix.all()==modified_A.all()):
    print('Correct.')
else:
    print('Incorrect.') 

[[ 4.  0. -1.]
 [ 0.  5. -7.]
 [ 1. -1. -1.]]
Correct.
